---
kind: Namespace
apiVersion: v1
metadata:
  name: blitzshare-redis-ns
  labels:
    name: blitzshare-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: file-share-ns
  name: blitzshare-redis-primary-deployment
  labels:
    name:  blitzshare-redis-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      name: blitzshare-redis-primary
  template:
    metadata:
      labels:
        name: blitzshare-redis-primary
    spec:
      subdomain: primary
      containers:
        - name: redis
          image: redis:3.2.0-alpine
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379
