apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  blitzshare-api-hpa
  namespace: blitzshare-ns
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blitzshare-api-dpl
  targetCPUUtilizationPercentage: 75