// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ApiKeychain is an autogenerated mock type for the ApiKeychain type
type ApiKeychain struct {
	mock.Mock
}

// IsValid provides a mock function with given fields: apiKey
func (_m *ApiKeychain) IsValid(apiKey *string) bool {
	ret := _m.Called(apiKey)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*string) bool); ok {
		r0 = rf(apiKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
