// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	db "blitzshare.api/app/services/db/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// GetApiKey provides a mock function with given fields: ctx, apiKey
func (_m *Querier) GetApiKey(ctx context.Context, apiKey string) (db.ApiKey, error) {
	ret := _m.Called(ctx, apiKey)

	var r0 db.ApiKey
	if rf, ok := ret.Get(0).(func(context.Context, string) db.ApiKey); ok {
		r0 = rf(ctx, apiKey)
	} else {
		r0 = ret.Get(0).(db.ApiKey)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
