// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// Get provides a mock function with given fields: otp
func (_m *Registry) Get(otp string) (string, error) {
	ret := _m.Called(otp)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(otp)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(otp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
