// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type ApiKey struct {
	ID        int64        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	ApiKey    string       `json:"api_key"`
	Enabled   bool         `json:"enabled"`
}
